HubSpot/hubspot-api-nodejs

- codegen/marketing/transactional/api/defaultApi.ts
Fix createToken method name in Marketing Transactional API
> Fix createToken method name in Marketing Transactional API (codegen only)

- sample-apps/imports-contacts-app/src/index.js
- sample-apps/imports-contacts-app/src/views/login.pug
> fix import + add oauth title

- README.md
Fixes https://github.com/HubSpot/hubspot-api-nodejs/issues/62
> Fix associations example of usage in README.md

- CHANGELOG.md
- package-lock.json
- package.json
The reason is regeneration of all clients
> bump version to 4.0.0

- sample-apps/companies-app/src/index.js
- sample-apps/companies-app/src/package.json
- sample-apps/companies-app/src/views/companies.pug
- sample-apps/contacts-app/src/index.js
- sample-apps/contacts-app/src/package.json
- sample-apps/contacts-app/src/views/contacts.pug
Update sdk version + add delete of entities (contacts and companies)
> review contacts and companies sample apps

- sample-apps/oauth-app/src/index.js
- sample-apps/oauth-app/src/package-lock.json
- sample-apps/oauth-app/src/package.json
- src/discovery/oauth/OauthDiscovery.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/76
> Add funcction "getAuthorizationUrl"

- sample-apps/oauth-app/src/index.js
- src/client.ts
- src/discovery/BaseDiscovery.ts
- src/discovery/automation/AutomationDiscovery.ts
- src/discovery/cms/CmsDiscovery.ts
- src/discovery/conversations/ConversationsDiscovery.ts
- src/discovery/crm/CrmDiscovery.ts
- src/discovery/events/EventsDiscovery.ts
- src/discovery/marketing/MarketingDiscovery.ts
- src/discovery/oauth/OauthDiscovery.ts
- src/discovery/webhooks/WebhooksDiscovery.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/76
> add set access token

- src/configuration/ApiClientConfigurator.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/143
> Iterable  middleware 

- CHANGELOG.md
https://github.com/HubSpot/hubspot-api-nodejs/issues/215
> Reorder Changelog

- src/client.ts
- src/discovery/BaseDiscovery.ts
- src/discovery/automation/AutomationDiscovery.ts
- src/discovery/cms/CmsDiscovery.ts
- src/discovery/cms/blogs/BlogsDiscovery.ts
- src/discovery/conversations/ConversationsDiscovery.ts
- src/discovery/crm/extensions/ExtensionsDiscovery.ts
- src/discovery/crm/objects/ObjectsDiscovery.ts
- src/discovery/marketing/MarketingDiscovery.ts
- src/discovery/settings/SettingsDiscovery.ts
- src/services/initObject.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/262
Memory usage was checked with process.memoryUsage()
main param is heapUsed (34.32 MB => 10 MB)
Before
```
rss 94.3 MB
heapTotal 55.53 MB
heapUsed 34.32 MB
external 1.46 MB
arrayBuffers 0.85 MB
```
After
```
rss 48.36 MB
heapTotal 17.3 MB
heapUsed 10.01 MB
external 0.63 MB
arrayBuffers 0.03 MB
```
> Optimization of memory usage 

- src/discovery/crm/companies/CompaniesDiscovery.ts
- src/discovery/crm/contacts/ContactsDiscovery.ts
- src/discovery/crm/deals/DealsDiscovery.ts
- src/discovery/crm/line_items/LineItemsDiscovery.ts
- src/discovery/crm/products/ProductsDiscovery.ts
- src/discovery/crm/quotes/QuotesDiscovery.ts
- src/discovery/crm/tickets/TicketsDiscovery.ts
> rm unnecessary lodash in Discoveries

- src/services/http/Auth.ts
- src/services/http/Request.ts
> ApiRequest: forIn to native and include only get from lodash

- src/discovery/oauth/OauthDiscovery.ts
- test/unit/authorizationUrl.spec.ts
> Remove Lodash from OauthDiscovery

- package-lock.json
- package.json
- src/configuration/ApiClientConfigurator.ts
- src/services/http/Auth.ts
- src/services/http/HttpClient.ts
- src/services/http/Request.ts
> use lodash.get and lodash.merge instead of lodash

- README.md
https://github.com/HubSpot/hubspot-api-nodejs/issues/246
> Update import example in README

- package-lock.json
- package.json
> rm btoa from packages list

- package-lock.json
- package.json
https://github.com/HubSpot/hubspot-api-nodejs/issues/208
> Move types/node-fetch from devDependencies to dependencies

- README.md
https://github.com/HubSpot/hubspot-api-nodejs/issues/307
> Update association example in README

- src/services/initObject.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/296
https://github.com/HubSpot/hubspot-api-nodejs/issues/284
> Fix discoveries object's initialization

- README.md
https://github.com/HubSpot/hubspot-api-nodejs/issues/171
> Add notice about reserved words to README

- src/discovery/crm/associations/AssociationsDiscovery.ts
- src/discovery/crm/associations/v4/AssociationsDiscovery.ts
- test/spec/crm/associations/associations.spec.ts
- test/spec/crm/associations/v4/associations.spec.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/199
> Add Associations Discovery

- README.md
https://github.com/HubSpot/hubspot-api-nodejs/issues/330
> Update audit logs example

- index.ts
- src/client.ts
- src/configuration/IConfiguration.ts
- src/configuration/constants.ts
- src/configuration/privateConstants.ts
- src/services/decorators/LimiterDecorator.ts
- src/services/getAll.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/254
> Rate limiter

- README.md
https://github.com/HubSpot/hubspot-api-nodejs/issues/254
> Rate limiting (README)

- src/discovery/crm/objects/ObjectsDiscovery.ts
- src/discovery/crm/objects/communications/CommunicationsDiscovery.ts
- test/spec/crm/objects/communications/communications.spec.ts
- test/spec/crm/objects/objects.spec.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/297
> Add CRM communications discovery

- src/configuration/ApiClientConfigurator.ts
- src/configuration/IConfiguration.ts
- src/services/IRequestContext.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/243
> Add ability to change httpAgent

- src/configuration/ApiClientConfigurator.ts
- src/configuration/IConfiguration.ts
- src/services/IRequestContext.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/243
> Add ability to change http agent

- README.md
https://github.com/HubSpot/hubspot-api-nodejs/issues/14
> Readme: Update sort example

- CHANGELOG.md
- package-lock.json
- package.json
https://github.com/HubSpot/hubspot-api-nodejs/issues/398
https://github.com/HubSpot/hubspot-api-nodejs/issues/394
> Bump version to 10.0.0

- README.md
https://github.com/HubSpot/hubspot-api-nodejs/issues/467
> README: Update CRM object search example.

- README.md
https://github.com/HubSpot/hubspot-api-nodejs/issues/466
> Added note about code examples to README.

- codegen/automation/actions/models/ObjectSerializer.ts
https://github.com/HubSpot/hubspot-api-nodejs/issues/427
> Automaion Action: added text/plain to supported media types.

- src/discovery/crm/objects/calls/CallsDiscovery.ts
- src/discovery/crm/objects/communications/CommunicationsDiscovery.ts
- src/discovery/crm/objects/emails/EmailsDiscovery.ts
- src/discovery/crm/objects/feedback_submissions/FeedbackSubmissionsDiscovery.ts
- src/discovery/crm/objects/goals/GoalsDiscovery.ts
- test/spec/crm/objects/calls/calls.spec.ts
- test/spec/crm/objects/communications/communications.spec.ts
- test/spec/crm/objects/emails/emails.spec.ts
- test/spec/crm/objects/feedback_submissions/feedback_submissions.spec.ts
- test/spec/crm/objects/goals/goals.spec.ts
> Update discoveries: CRM Calls, Emails, Feedback Submissions, Communications and Goals
